.Dd August 17, 2011
.Dt APROPOS 1
.Os
.Sh NAME
.Nm apropos
.Nd Search across the complete content of man pages.
.Sh SYNOPSIS
.Nm
.Op Fl 123456789p
.Sh DESCRIPTION
The
.Nm
utility performs a full text search across the complete content of man pages. 
It uses the FTS engine of Sqlite to perform the search. The database is
created with the help of
.Xr makemandb 1
utility.
.Pp
This implementation of
.Nm
utility is more sophisticated than the classical version of
.Nm
Like modern search applications, it uses advanced techniques like stemming,
and term weighting to rank the matching results in decreasing order of 
relevance.
By default
.Nm 
will display only top 10 matches in the output.
.Pp
It supports following options:
.Bl -tag -width indent
.It Fl 1
Search only within section 1 manual pages.
.It Fl 2
Search only within section 2 manual pages.
.It Fl 3
Search only within section 3 manual pages.
.It Fl 4
Search only within section 4 manual pages.
.It Fl 5
Search only within section 5 manual pages.
.It Fl 6
Search only within section 6 manual pages.
.It Fl 7
Search only within section 7 manual pages.
.It Fl 8
Search only within section 8 manual pages.
.It Fl 9
Search only within section 9 manual pages.
.It Fl p
This option may be used to overcome the default limit of 10 results 
in the output. It will make 
.Nm
to display all matching results and also pipe them to a pager (
.Xr more 1
is default).
.Sh FILES
.Bl -hang -width -compact
.Pa /var/db/man.db
The Sqlite FTS database which maintains an index of the manual pages.
.Sh SEE ALSO
.Xr man 1 ,
.Xr makemandb 1
.Sh AUTHORS
.An Abhinav Upadhyay
.Sh BUGS
At the moment 
.Xr makemandb 1
is unable to parse the escape sequences in
.Xr man 7 
pages, therefore at times you might see the snippets of the matching 
text mixed with escape sequences, making it a bit unreadable. This
should be fixed in upcoming versions.
