.Dd August 17, 2011
.Dt APROPOS-UTILS 3
.Os
.Sh NAME
.Nm init_db ,
.Nm close_db ,
.Nm run_query ,
.Nm run_query_html ,
.Nm run_query_pager
.Sh SYNOPSIS
.In apropos-utils.h
.Ft sqlite3 *
.Fn init_db "int db_flag"
.Ft void
.Fn close_db "sqlite3 *db"
.Ft int
.Fn run_query "sqlite3 *db" "const char *snippet_args[3]" "query_args *args"
.Ft int
.Fn run_query_html "sqlite3 *db" "query_args *args"
.Ft int
.Fn run_query_pager "sqlite3 *db" "query_args *args"
.Sh DESCRIPTION
These functions all live in the
.Pa apropos-utils.h
header file.
They operate on
.Pa /var/db/man.db
which is an Sqlite database containing a full text search index of the manual 
pages. The functions provide an easy to use interface to query the database and 
develop applications on top of it.
.Sh SEE ALSO
.Xr init_db 3 ,
.Xr close_db 3 ,
.Xr run_query 3 ,
.Xr run_query_html 3 ,
.Xr run_query_pager 3
.Sh AUTHORS
.An Abhinav Upadhyay
