.Dd August 17, 2011
.Dt INIT_DB 3
.Os
.Sh NAME
.Nm init_db
.Sh SYNOPSIS
.In apropos-utils.h
.Ft sqlite3 *
.Fn init_db "int db_flag"
.Sh DESCRIPTION
The
.Fn init_db
function will try to initialize a connection to apropos.db which is an 
Sqlite database and return a pointer to sqlite to use that connection. 
The connection should subsequentaly be closed by calling 
.Fn close_db
which will also release any resources being used by it.
.Pp
The argument
.Fa db_flag
should be supplied one of the following macros as it's value:
.Bl -hang -width 
.It Dv DB_READONLY
This will open the database in read only mode. Use this when you simply 
want to query the database.
.It Dv DB_WRITE
This will open the database in read and write mode. 
.It Dv DB_CREATE
This will open the database in read/write mode, and this will also create 
the database schema if it does not exist already.
.Sh FILES
.Bl -hang -width /var/db/man.db -compact
.It Pa /var/db/man.db
The Sqlite FTS database which maintains an index of the manual pages.
.Sh RETURN VALUES
On successful execution the
.Fn init_db
function will return a pointer to sqlite3 which represents a connection to 
the database.
.Pp
In case the file
.Pa /var/db/man.db does not exist and
.Dv DB_CREATE
is not used as a value of
.Fa db_flag
then
.Dv NULL
will be returned.
.Sh SEE ALSO
.Xr apropos-utils 3 ,
.Xr close_db 3 ,
.Xr run_query 3 ,
.Xr run_query_html ,
.Xr run_query_pager
.Sh AUTHORS
.An Abhinav Upadhyay

